In [1]:
%matplotlib inline
from sklearn import datasets
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./bridgeconbine.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: './bridgeconbine.csv'

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         109 non-null    object
 1   deflection   109 non-null    float64
 2   temperature  109 non-null    float64
 3   OW1          109 non-null    float64
 4   OW2          109 non-null    float64
 5   T1(1-3)      109 non-null    float64
 6   T1(2-4)      109 non-null    float64
 7   T2(1-3)      109 non-null    float64
 8   T2(2-4)      109 non-null    float64
 9   T3(1-3)      109 non-null    float64
 10  T3(2-4)      109 non-null    float64
 11  T4(1-3)      109 non-null    float64
 12  T4(2-4)      109 non-null    float64
 13  T5(1-3)      109 non-null    float64
 14  T5(2-4)      109 non-null    float64
 15  T6(1-3)      109 non-null    float64
 16  T6(2-4)      109 non-null    float64
 17  number       109 non-null    int64
dtypes: float64(16), int64(1), object(1)
memory usage: 15.5+ KB

In [5]:
df.describe()

,deflection,temperature,OW1,OW2,T1(1-3),T1(2-4),T2(1-3),T2(2-4),T3(1-3),T3(2-4),T4(1-3),T4(2-4),T5(1-3),T5(2-4),T6(1-3),T6(2-4),number
count,109.00000,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000
mean,586.18055,22.588073,-1.467706,-6.587523,0.000302,-0.000067,0.000740,0.000172,-0.000803,0.001278,-0.000274,0.000072,0.000264,-0.001201,-0.000250,0.000343,36353.009174
std,2.42929,5.806713,0.504285,0.984695,0.000257,0.000171,0.000659,0.000205,0.000588,0.000729,0.000143,0.000198,0.000356,0.000762,0.000135,0.000193,11438.434614
min,580.20000,7.700000,-2.840000,-9.400000,-0.000620,-0.000340,-0.000160,-0.000800,-0.001740,0.000000,-0.000780,-0.001020,-0.000400,-0.002160,-0.000720,-0.000320,17637.000000
25%,584.31000,17.900000,-1.780000,-7.210000,0.000160,-0.000160,0.000300,0.000060,-0.001380,0.000860,-0.000300,-0.000020,-0.000020,-0.001820,-0.000320,0.000280,28817.000000
50%,586.44000,23.300000,-1.440000,-6.360000,0.000320,-0.000100,0.000620,0.000160,-0.000840,0.001320,-0.000240,0.000040,0.000200,-0.001460,-0.000220,0.000380,32481.000000
75%,587.97000,27.400000,-1.140000,-5.870000,0.000460,0.000020,0.000960,0.000300,-0.000280,0.001880,-0.000180,0.000180,0.000580,-0.000780,-0.000160,0.000460,43399.000000
max,594.63000,33.000000,-0.400000,-4.500000,0.000860,0.000500,0.002080,0.000640,0.000120,0.002540,-0.000020,0.000520,0.000980,0.000640,0.000040,0.000680,77808.000000

In [7]:
from sklearn.model_selection import train_test_split
features = ['temperature', 'OW1', 'OW2', 'T1(1-3)','T1(2-4)','T2(1-3)','T2(2-4)','T3(1-3)','T3(2-4)','T4(1-3)','T4(2-4)','T5(1-3)','T5(2-4)','T6(1-3)','T6(2-4)','number'] 
X = df[features]
y = df['deflection']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [8]:
from sklearn.linear_model import LinearRegression#線性回歸
clf1 = LinearRegression()

clf1.fit(X_train, y_train)

LinearRegression()

In [9]:
from sklearn.linear_model import LinearRegression
clf1 = LinearRegression()
clf1.fit(X, y)
print('y = {:.4f} * x + {:.4f}'.format(clf1.coef_[0], clf1.intercept_))

y = 0.3491 * x + 579.2472

In [10]:
from sklearn.neighbors import NearestNeighbors
clf2 = NearestNeighbors()

clf2.fit(X_train, y_train)

NearestNeighbors()

In [16]:
X_train

,temperature,OW1,OW2,T1(1-3),T1(2-4),T2(1-3),T2(2-4),T3(1-3),T3(2-4),T4(1-3),T4(2-4),T5(1-3),T5(2-4),T6(1-3),T6(2-4),number
39,25.3,-1.85,-7.44,0.00028,0.00004,0.00066,0.00010,-0.00086,0.00130,-0.00068,0.00010,0.00034,-0.00154,-0.00006,0.00028,50826
8,26.0,-1.76,-6.05,0.00022,0.00002,0.00054,0.00030,-0.00018,0.00094,-0.00018,-0.00002,0.00010,-0.00068,-0.00030,0.00034,26023
41,23.0,-0.98,-6.65,0.00038,-0.00004,0.00064,0.00008,-0.00086,0.00146,-0.00030,0.00012,0.00024,-0.00168,-0.00010,0.00044,39462
35,19.3,-2.10,-6.84,0.00034,0.00002,0.00044,0.00010,-0.00090,0.00100,-0.00020,0.00004,0.00026,-0.00170,-0.00016,0.00038,29184
71,21.9,-1.22,-5.92,0.00040,-0.00016,0.00138,0.00036,-0.00132,0.00210,-0.00026,0.00024,0.00062,-0.00188,-0.00010,0.00030,41251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,28.7,-1.24,-6.12,0.00048,-0.00022,0.00100,0.00018,-0.00140,0.00192,-0.00026,0.00008,0.00054,-0.00186,-0.00004,0.00036,28817
17,32.0,-1.55,-8.40,0.00018,0.00008,0.00048,0.00006,-0.00036,0.00094,-0.00016,0.00006,0.00008,-0.00102,-0.00010,0.00014,39462
22,17.0,-1.70,-8.40,0.00028,-0.00018,0.00008,-0.00008,-0.00050,0.00088,-0.00030,-0.00002,-0.00032,-0.00124,-0.00034,0.00030,23712
88,19.7,-0.64,-4.67,0.00054,-0.00032,0.00208,0.00046,-0.00160,0.00246,-0.00012,0.00052,0.00090,-0.00186,-0.00016,0.00044,34833
1,28.0,-2.84,-7.20,0.00014,-0.00006,0.00044,0.00008,-0.00006,0.00066,-0.00012,-0.00018,-0.00002,-0.00042,-0.00016,0.00046,43399

In [17]:
X_test

,temperature,OW1,OW2,T1(1-3),T1(2-4),T2(1-3),T2(2-4),T3(1-3),T3(2-4),T4(1-3),T4(2-4),T5(1-3),T5(2-4),T6(1-3),T6(2-4),number
51,20.3,-0.66,-5.75,0.00044,-0.00014,0.00064,0.00006,-0.00126,0.00156,-0.00026,0.00004,0.00022,-0.00192,-0.00028,0.00048,50826
49,27.5,-0.83,-6.12,0.00044,-0.00012,0.00062,0.00000,-0.00122,0.00154,-0.00022,0.00002,0.00018,-0.00170,-0.00028,0.00038,43399
92,25.4,-1.77,-5.80,-0.00004,0.00006,-0.00008,0.00020,0.00008,0.00006,-0.00038,0.00016,-0.00034,0.00018,-0.00024,0.00024,58458
6,27.0,-2.10,-6.10,0.00028,-0.00010,0.00056,0.00030,-0.00022,0.00086,-0.00020,-0.00012,0.00000,-0.00090,-0.00044,0.00034,31999
44,9.9,-1.12,-6.89,0.00022,-0.00016,0.00062,0.00006,-0.00078,0.00146,-0.00022,0.00002,0.00008,-0.00146,-0.00018,0.00060,26023
42,17.9,-1.03,-6.69,0.00022,-0.00012,0.00072,0.00020,-0.00094,0.00132,-0.00032,-0.00002,0.00006,-0.00164,-0.00020,0.00056,31999
86,26.2,-1.33,-5.77,0.00058,-0.00024,0.00202,0.00046,-0.00166,0.00246,-0.00012,0.00044,0.00094,-0.00186,-0.00026,0.00044,25601
103,16.7,-0.78,-5.25,-0.00006,0.00030,-0.00004,0.00020,-0.00004,0.00002,-0.00038,-0.00018,0.00024,-0.00036,-0.00058,0.00054,60699
40,24.6,-1.85,-7.00,0.00042,0.00010,0.00060,0.00014,-0.00094,0.00142,-0.00040,0.00024,0.00028,-0.00170,-0.00014,0.00040,41251
83,27.2,-1.68,-6.32,0.00080,-0.00034,0.00196,0.00056,-0.00152,0.00220,-0.00028,0.00040,0.00068,-0.00184,-0.00034,0.00044,37911
11,18.5,-1.75,-9.40,0.00012,-0.00004,0.00022,0.00030,-0.00028,0.00090,-0.00024,-0.00002,-0.00020,-0.00076,-0.00044,0.00030,29184
43,15.2,-1.40,-7.10,0.00020,-0.00016,0.00068,0.00012,-0.00090,0.00138,-0.00026,0.00000,0.00006,-0.00156,-0.00022,0.00058,24841
60,27.7,-1.50,-6.59,0.00050,-0.00012,0.00094,0.00012,-0.00138,0.00202,-0.00016,0.00008,0.00054,-0.00174,-0.00018,0.00026,28028
12,20.5,-1.85,-8.87,0.00014,-0.00008,0.00032,0.00030,-0.00036,0.00096,-0.00026,-0.00012,-0.00020,-0.00070,-0.00046,0.00038,35282
48,27.8,-0.50,-6.20,0.00050,-0.00012,0.00072,-0.00012,-0.00120,0.00172,-0.00026,0.00002,0.00036,-0.00192,-0.00018,0.00026,35282
104,16.4,-0.91,-5.59,-0.00026,0.00040,0.00086,0.00012,-0.00018,0.00028,-0.00042,-0.00102,0.00026,0.00014,-0.00040,-0.00014,77808
23,17.3,-1.82,-8.10,0.00020,-0.00022,0.00024,0.00010,-0.00048,0.00092,-0.00026,-0.00004,-0.00018,-0.00122,-0.00024,0.00034,29184
59,23.1,-1.50,-6.42,0.00046,-0.00008,0.00086,0.00006,-0.00140,0.00186,-0.00022,0.00012,0.00044,-0.00184,-0.00026,0.00032,29184
9,27.6,-1.63,-6.00,0.00024,-0.00008,0.00064,0.00018,-0.00028,0.00086,-0.00020,-0.00008,0.00004,-0.00092,-0.00072,0.00034,29248
20,26.3,-1.40,-7.94,0.00030,-0.00012,0.00032,-0.00008,-0.00034,0.00100,-0.00034,-0.00006,-0.00018,-0.00124,-0.00036,0.00036,26023
90,12.5,-1.75,-5.74,-0.00010,0.00004,-0.00014,0.00018,0.00012,0.00002,-0.00030,0.00022,-0.00018,0.00010,-0.00018,0.00026,37573
64,25.5,-1.72,-6.50,0.00050,-0.00008,0.00108,0.00018,-0.00144,0.00186,-0.00018,0.00006,0.00074,-0.00202,-0.00014,0.00042,29607

In [18]:
df_train, df_test = train_test_split(df, test_size=0.25, random_state=0)
print('Size of train dataframe: ', df_train.shape[0])
print('Size of test dataframe: ', df_test.shape[0])

Size of train dataframe:  81
Size of test dataframe:  28

In [21]:
# Create a flag for label masking
df_train['temperature'] = True
df_train.loc[df_train.sample(frac=0.05, random_state=0).index, 'temperature'] = False

# Create a new target colum with labels. The 1's and 0's are original labels and -1 represents unlabeled (masked) data
df_train['Dependents_Target']=df_train.apply(lambda x: x['OW1'] if x['temperature']==False else -1, axis=1)

# Show target value distribution
print('Target Value Distribution:')
print(df_train['Dependents_Target'].value_counts())

Target Value Distribution:
-1.00    77
-1.22     1
-1.70     1
-0.55     1
-1.85     1
Name: Dependents_Target, dtype: int64

In [25]:
# Create a scatter plot
fig = df.deflection(df_train, x='temperature', y='MntWines', opacity=1, color=df_train['Dependents_Target'].astype(str),
                 color_discrete_sequence=['lightgrey', 'red', 'blue'],
                )

# Change chart background color
fig.update_layout(dict(plot_bgcolor = 'white'))

# Update axes lines
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='white', 
                 zeroline=True, zerolinewidth=1, zerolinecolor='white', 
                 showline=True, linewidth=1, linecolor='white')

fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='white', 
                 zeroline=True, zerolinewidth=1, zerolinecolor='white', 
                 showline=True, linewidth=1, linecolor='white')

# Set figure title
fig.update_layout(title_text="Marketing Campaign Training Data - Labeled vs. Unlabeled")

# Update marker size
fig.update_traces(marker=dict(size=5))

fig.show()

TypeError: 'Series' object is not callable